app:
  new_flag_img: '![news](https://github.com/CasualRO/CasualRO/blob/master/imgs/new.gif)'
  activity_num: 10            # 展示的活动项数
  article_num: 10             # 展示的文章项数
  skip_repos:
    - '.*?demo.*'
    - 'crop-circles'
    
github:
  proxy: "<%= ENV['PROXY'] %>"  # 连接到 Github 的代理服务，如： http://127.0.0.1:8888, socks5://127.0.0.1:1088
  owner: 'CasualRO'
  url: 'https://github.com'
  graphql: 'https://api.github.com/graphql'
  gtk: "<%= ENV['GTK'] %>"      # Github Token
